development:
  adapter: postgresql
  database: new_loomio_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: new_loomio_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: new_loomio_production
  encoding: unicode
  pool: 5
  timeout: 5000